Watching for file changes with StatReloader
Watching for file changes with StatReloader
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /submit_homework/
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /submit_homework/
"POST /submit_homework/ HTTP/1.1" 403 2569
"POST /submit_homework/ HTTP/1.1" 403 2569
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /submit_homework/ HTTP/1.1" 200 46
"POST /submit_homework/ HTTP/1.1" 200 46
"POST /submit_homework/ HTTP/1.1" 200 46
"POST /submit_homework/ HTTP/1.1" 200 46
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /submit_homework/ HTTP/1.1" 200 46
"POST /submit_homework/ HTTP/1.1" 200 46
"POST /submit_homework/ HTTP/1.1" 200 46
"POST /submit_homework/ HTTP/1.1" 200 46
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /submit_homework/ HTTP/1.1" 200 56
"POST /submit_homework/ HTTP/1.1" 200 56
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /latests/
Not Found: /latests/
"GET /latests/ HTTP/1.1" 404 2737
"GET /latests/ HTTP/1.1" 404 2737
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\web_project\settings.py changed, reloading.
C:\Users\Namai\Desktop\web-django\web_project\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\web_project\settings.py changed, reloading.
C:\Users\Namai\Desktop\web-django\web_project\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"OPTIONS /handle_classes/ HTTP/1.1" 200 0
"OPTIONS /handle_classes/ HTTP/1.1" 200 0
"GET /handle_classes/ HTTP/1.1" 200 2
"GET /handle_classes/ HTTP/1.1" 200 2
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
"POST /handle_classes/ HTTP/1.1" 403 2569
"POST /handle_classes/ HTTP/1.1" 403 2569
"OPTIONS /login/ HTTP/1.1" 200 0
"OPTIONS /login/ HTTP/1.1" 200 0
Unauthorized: /login/
Unauthorized: /login/
"POST /login/ HTTP/1.1" 401 66
"POST /login/ HTTP/1.1" 401 66
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"OPTIONS /signup/ HTTP/1.1" 200 0
"OPTIONS /signup/ HTTP/1.1" 200 0
Internal Server Error: /signup/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 49, in signup_user
    user = CustomUser.objects.create_user(first_name=name, last_name=surname,email=email, password=password, role=role)
TypeError: create_user() missing 1 required positional argument: 'username'
Internal Server Error: /signup/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 49, in signup_user
    user = CustomUser.objects.create_user(first_name=name, last_name=surname,email=email, password=password, role=role)
TypeError: create_user() missing 1 required positional argument: 'username'
"POST /signup/ HTTP/1.1" 500 74959
"POST /signup/ HTTP/1.1" 500 74959
Internal Server Error: /signup/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 49, in signup_user
    user = CustomUser.objects.create_user(first_name=name, last_name=surname,email=email, password=password, role=role)
TypeError: create_user() missing 1 required positional argument: 'username'
Internal Server Error: /signup/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 49, in signup_user
    user = CustomUser.objects.create_user(first_name=name, last_name=surname,email=email, password=password, role=role)
TypeError: create_user() missing 1 required positional argument: 'username'
"POST /signup/ HTTP/1.1" 500 74922
"POST /signup/ HTTP/1.1" 500 74922
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"OPTIONS /signup/ HTTP/1.1" 200 0
"OPTIONS /signup/ HTTP/1.1" 200 0
"POST /signup/ HTTP/1.1" 200 225
"POST /signup/ HTTP/1.1" 200 225
"OPTIONS /handle_classes/ HTTP/1.1" 200 0
"OPTIONS /handle_classes/ HTTP/1.1" 200 0
"GET /handle_classes/ HTTP/1.1" 200 2
"GET /handle_classes/ HTTP/1.1" 200 2
"OPTIONS /handle_homework/ HTTP/1.1" 200 0
"OPTIONS /handle_homework/ HTTP/1.1" 200 0
"GET /handle_homework/ HTTP/1.1" 200 53
"GET /handle_homework/ HTTP/1.1" 200 53
"GET /handle_homework/ HTTP/1.1" 200 53
"GET /handle_homework/ HTTP/1.1" 200 53
"GET /handle_homework/ HTTP/1.1" 200 53
"GET /handle_homework/ HTTP/1.1" 200 53
"GET /handle_classes/ HTTP/1.1" 200 2
"GET /handle_classes/ HTTP/1.1" 200 2
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
"POST /handle_classes/ HTTP/1.1" 403 2569
"POST /handle_classes/ HTTP/1.1" 403 2569
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
"POST /handle_classes/ HTTP/1.1" 403 2569
"POST /handle_classes/ HTTP/1.1" 403 2569
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
"POST /handle_classes/ HTTP/1.1" 403 2569
"POST /handle_classes/ HTTP/1.1" 403 2569
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
"POST /handle_classes/ HTTP/1.1" 403 2569
"POST /handle_classes/ HTTP/1.1" 403 2569
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
Forbidden (Origin checking failed - http://localhost:3000 does not match any trusted origins.): /handle_classes/
"POST /handle_classes/ HTTP/1.1" 403 2569
"POST /handle_classes/ HTTP/1.1" 403 2569
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /handle_classes/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 130, in handle_classes
    classs = Class.object.create(title=title)
AttributeError: type object 'Class' has no attribute 'object'
Internal Server Error: /handle_classes/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 130, in handle_classes
    classs = Class.object.create(title=title)
AttributeError: type object 'Class' has no attribute 'object'
"POST /handle_classes/ HTTP/1.1" 500 74271
"POST /handle_classes/ HTTP/1.1" 500 74271
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /handle_classes/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'title' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 131, in handle_classes
    classs.save()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'title' cannot be null")
Internal Server Error: /handle_classes/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'title' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 131, in handle_classes
    classs.save()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'title' cannot be null")
"POST /handle_classes/ HTTP/1.1" 500 172855
"POST /handle_classes/ HTTP/1.1" 500 172855
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /handle_classes/ HTTP/1.1" 200 56
"POST /handle_classes/ HTTP/1.1" 200 56
"GET /handle_classes/ HTTP/1.1" 200 26
"GET /handle_classes/ HTTP/1.1" 200 26
"OPTIONS /handle_classes/undefined/ HTTP/1.1" 200 0
"OPTIONS /handle_classes/undefined/ HTTP/1.1" 200 0
Not Found: /handle_classes/undefined/
Not Found: /handle_classes/undefined/
"GET /handle_classes/undefined/ HTTP/1.1" 404 3240
"GET /handle_classes/undefined/ HTTP/1.1" 404 3240
"GET /handle_classes/ HTTP/1.1" 200 26
"GET /handle_classes/ HTTP/1.1" 200 26
"OPTIONS /handle_classes/1/ HTTP/1.1" 200 0
"OPTIONS /handle_classes/1/ HTTP/1.1" 200 0
"GET /handle_classes/1/ HTTP/1.1" 200 15
"GET /handle_classes/1/ HTTP/1.1" 200 15
Forbidden: /handle_classes/1/
Forbidden: /handle_classes/1/
"PUT /handle_classes/1/ HTTP/1.1" 403 67
"PUT /handle_classes/1/ HTTP/1.1" 403 67
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Forbidden: /handle_classes/1/
Forbidden: /handle_classes/1/
"PUT /handle_classes/1/ HTTP/1.1" 403 67
"PUT /handle_classes/1/ HTTP/1.1" 403 67
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Forbidden: /handle_classes/1/
Forbidden: /handle_classes/1/
"PUT /handle_classes/1/ HTTP/1.1" 403 67
"PUT /handle_classes/1/ HTTP/1.1" 403 67
"OPTIONS /login/ HTTP/1.1" 200 0
"OPTIONS /login/ HTTP/1.1" 200 0
Unauthorized: /login/
Unauthorized: /login/
"POST /login/ HTTP/1.1" 401 66
"POST /login/ HTTP/1.1" 401 66
Unauthorized: /login/
Unauthorized: /login/
"POST /login/ HTTP/1.1" 401 66
"POST /login/ HTTP/1.1" 401 66
Bad Request: /signup/
Bad Request: /signup/
"POST /signup/ HTTP/1.1" 400 36
"POST /signup/ HTTP/1.1" 400 36
"POST /signup/ HTTP/1.1" 200 232
"POST /signup/ HTTP/1.1" 200 232
Unauthorized: /login/
Unauthorized: /login/
"POST /login/ HTTP/1.1" 401 66
"POST /login/ HTTP/1.1" 401 66
Unauthorized: /login/
Unauthorized: /login/
"POST /login/ HTTP/1.1" 401 66
"POST /login/ HTTP/1.1" 401 66
Unauthorized: /login/
Unauthorized: /login/
"POST /login/ HTTP/1.1" 401 66
"POST /login/ HTTP/1.1" 401 66
Unauthorized: /login/
Unauthorized: /login/
"POST /login/ HTTP/1.1" 401 66
"POST /login/ HTTP/1.1" 401 66
Unauthorized: /login/
Unauthorized: /login/
"POST /login/ HTTP/1.1" 401 66
"POST /login/ HTTP/1.1" 401 66
"POST /signup/ HTTP/1.1" 200 230
"POST /signup/ HTTP/1.1" 200 230
Bad Request: /signup/
Bad Request: /signup/
"POST /signup/ HTTP/1.1" 400 36
"POST /signup/ HTTP/1.1" 400 36
"POST /signup/ HTTP/1.1" 200 230
"POST /signup/ HTTP/1.1" 200 230
"GET /handle_homework/ HTTP/1.1" 200 53
"GET /handle_homework/ HTTP/1.1" 200 53
"GET /handle_classes/ HTTP/1.1" 200 26
"GET /handle_classes/ HTTP/1.1" 200 26
"GET /handle_classes/1/ HTTP/1.1" 200 15
"GET /handle_classes/1/ HTTP/1.1" 200 15
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"PUT /handle_classes/1/ HTTP/1.1" 200 26
"PUT /handle_classes/1/ HTTP/1.1" 200 26
"PUT /handle_classes/1/ HTTP/1.1" 200 26
"PUT /handle_classes/1/ HTTP/1.1" 200 26
"GET /handle_classes/1/ HTTP/1.1" 200 17
"GET /handle_classes/1/ HTTP/1.1" 200 17
"GET /handle_classes/1/ HTTP/1.1" 200 17
"GET /handle_classes/1/ HTTP/1.1" 200 17
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"OPTIONS /handle_students/1/ HTTP/1.1" 200 0
"OPTIONS /handle_students/1/ HTTP/1.1" 200 0
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_students/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 234, in handle_students
    students_in_class = CustomUser.objects.filter(studentclass__classs_id=cid)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'studentclass' into field. Choices are: classs, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, results, role, school, school_id, student, user_permissions, username
Internal Server Error: /handle_students/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 234, in handle_students
    students_in_class = CustomUser.objects.filter(studentclass__classs_id=cid)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'studentclass' into field. Choices are: classs, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, results, role, school, school_id, student, user_permissions, username
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_students/1/ HTTP/1.1" 500 21997
"GET /handle_students/1/ HTTP/1.1" 500 21997
Internal Server Error: /handle_students/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 234, in handle_students
    students_in_class = CustomUser.objects.filter(studentclass__classs_id=cid)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'studentclass' into field. Choices are: classs, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, results, role, school, school_id, student, user_permissions, username
Internal Server Error: /handle_students/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 234, in handle_students
    students_in_class = CustomUser.objects.filter(studentclass__classs_id=cid)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'studentclass' into field. Choices are: classs, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, results, role, school, school_id, student, user_permissions, username
"GET /handle_students/1/ HTTP/1.1" 500 21997
"GET /handle_students/1/ HTTP/1.1" 500 21997
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
C:\Users\Namai\Desktop\web-django\web_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"OPTIONS /handle_students/0/1/ HTTP/1.1" 200 0
"OPTIONS /handle_students/0/1/ HTTP/1.1" 200 0
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/ HTTP/1.1" 200 28
"GET /handle_classes/ HTTP/1.1" 200 28
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/ HTTP/1.1" 200 28
"GET /handle_classes/ HTTP/1.1" 200 28
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
Internal Server Error: /handle_classes/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 178, in handle_classes_id
    classs = Class.objects.get(pk=pk)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'homework_app_class.teacher_id' in 'field list'")
"GET /handle_classes/1/ HTTP/1.1" 500 23361
"GET /handle_classes/1/ HTTP/1.1" 500 23361
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /handle_classes/ HTTP/1.1" 200 28
"GET /handle_classes/ HTTP/1.1" 200 28
"GET /handle_classes/1/ HTTP/1.1" 200 17
"GET /handle_classes/1/ HTTP/1.1" 200 17
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_classes/1/ HTTP/1.1" 200 17
"GET /handle_classes/1/ HTTP/1.1" 200 17
Not Found: /handle_students/0/1/
Not Found: /handle_students/0/1/
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"GET /handle_students/0/1/ HTTP/1.1" 404 3409
"OPTIONS /handle_students_class/0/1/ HTTP/1.1" 200 0
"OPTIONS /handle_students_class/0/1/ HTTP/1.1" 200 0
"GET /handle_classes/1/ HTTP/1.1" 200 17
"GET /handle_classes/1/ HTTP/1.1" 200 17
Internal Server Error: /handle_students_class/0/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 234, in handle_students_class
    students_in_class = CustomUser.objects.filter(studentclass__classs_id=cid)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'studentclass' into field. Choices are: classs, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, results, role, school, school_id, student, user_permissions, username
Internal Server Error: /handle_students_class/0/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 234, in handle_students_class
    students_in_class = CustomUser.objects.filter(studentclass__classs_id=cid)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'studentclass' into field. Choices are: classs, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, results, role, school, school_id, student, user_permissions, username
"GET /handle_students_class/0/1/ HTTP/1.1" 500 22041
"GET /handle_students_class/0/1/ HTTP/1.1" 500 22041
"GET /handle_classes/1/ HTTP/1.1" 200 17
"GET /handle_classes/1/ HTTP/1.1" 200 17
Internal Server Error: /handle_students_class/0/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 234, in handle_students_class
    students_in_class = CustomUser.objects.filter(studentclass__classs_id=cid)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'studentclass' into field. Choices are: classs, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, results, role, school, school_id, student, user_permissions, username
Internal Server Error: /handle_students_class/0/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 234, in handle_students_class
    students_in_class = CustomUser.objects.filter(studentclass__classs_id=cid)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'studentclass' into field. Choices are: classs, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, results, role, school, school_id, student, user_permissions, username
"GET /handle_students_class/0/1/ HTTP/1.1" 500 22041
"GET /handle_students_class/0/1/ HTTP/1.1" 500 22041
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /handle_classes/1/ HTTP/1.1" 200 17
"GET /handle_classes/1/ HTTP/1.1" 200 17
Internal Server Error: /handle_students_class/0/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 234, in handle_students_class
    students_in_class = CustomUser.objects.filter(studentclass__classs__id=cid)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'studentclass' into field. Choices are: classs, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, results, role, school, school_id, student, user_permissions, username
Internal Server Error: /handle_students_class/0/1/
Traceback (most recent call last):
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\homework_app\views.py", line 234, in handle_students_class
    students_in_class = CustomUser.objects.filter(studentclass__classs__id=cid)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Namai\Desktop\web-django\.venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'studentclass' into field. Choices are: classs, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, results, role, school, school_id, student, user_permissions, username
"GET /handle_students_class/0/1/ HTTP/1.1" 500 22042
"GET /handle_students_class/0/1/ HTTP/1.1" 500 22042
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
C:\Users\Namai\Desktop\web-django\homework_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
